services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    tty: true
    stdin_open: true
    user: ${HOST_UID:-1000}:${HOST_GID:-1000}
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
