name: Cross-Platform Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Combined build job for all platforms using matrix strategy
  build:
    name: Build All Platforms
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install common build dependencies
      run: |
        # Verify clang installation
        clang --version
    
    - name: Build Linux x86_64
      run: ./scripts/build.sh linux-x86
      
    # Upload artifacts
    - name: Upload Linux x86_64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-x86-binaries
        path: build/linux-x86/bin/
        retention-days: 1


  # Test jobs for each platform
  test-linux-x86:
    name: Test Linux x86_64
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Linux x86_64 artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux-x86-binaries
        path: build/linux-x86/bin/
      
    - name: Test Linux x86_64
      run: ./scripts/test.sh linux-x86
